
version: "3.3"

services:
  jupyter:
    build:
      context: .
    # To use a different port of host, change the first 8888.
    ports:
      - "9999:8888"
    volumes:
      - type: "bind"
        source: ./../../examples
        target: /examples
